on:
 push:
   branches:
    - main
    - feature/*
    - release/*
    pull_request:
      branches:
      - main
      - feature/*
      - release/*
 jobs:
   build-and-test
    runs-on: ubuntu-latest
    steps:
    
    
