on:
 push:
   branches:
    - main
    - feature/*
    - release/*
    pull_request:
      branches:
      - main
      - feature/*
      - release/*
 jobs:
   build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
    run:
    echo "Installing dependencies"
    npm install
    - name : Build
    run:
    echo "Building project..."
    npm run build
    - name: Test
    run:
    echo "Testing project..."
    npm run test
    - name: Publishing test results
    uses: actions/upload-artifact@v3
    with:
    name: test-results
    path: test reports/
    -name: Build docker image
    run:
    docker build -t yourusername/yourimage:latest .
    - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
    username: $ {{ secrets.DOCKER_USERNAME}}
    password: $ {{ secrets.DOCKER_PASSWORD}}
    - name: Push Docker image
    run:
    docker push yourusername/yourimage:latest
    
 
    
    
